#!/usr/bin/env bash
set -euo pipefail

if [[ -v DEBUG ]]; then
	set -x
fi

###################
# PARSE ARGUMENTS #
###################

basename="$(basename "$0")"

if [ "$#" -ne 0 ]; then
	echo "Expected zero arguments."
	exit 1
fi

#########
# SETUP #
#########
cd "$(dirname "$0")"

##############
# MAIN LOGIC #
##############

python3 -m serial.tools.miniterm /dev/ttyUSB0
