[package]
name = "itj_videogame_controller_firmware"
version = "0.2.0"
authors = ["Ivan Johnson <git@IvanJohnson.net>"]
edition = "2021"
publish = false

[dependencies]
embedded-hal = "1.0"
panic-halt = "1.0.0"
usb-device = "0.3.2"
usbd-hid = "0.9"

# TODO: remove, eventually?
ufmt = "0.2.0"

[dependencies.arduino-hal]
# I'm working on adding USB support to avr-hal:
# https://github.com/Rahix/avr-hal/pull/694
#
# This is my dev branch:
git = "https://github.com/Ivan-Johnson/avr-hal"
branch = "usb"
features = ["arduino-micro"]
